# Generated by Django 2.2 on 2020-05-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_libro_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
