# Generated by Django 2.2 on 2020-05-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0004_auto_20200514_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='Codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
