# Generated by Django 2.2 on 2020-05-15 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0005_auto_20200514_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Localizacion', models.CharField(max_length=30)),
                ('Libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblio.Libro')),
            ],
        ),
    ]
