# Generated by Django 2.2 on 2020-05-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0007_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplar',
            name='Usuarios',
            field=models.ManyToManyField(to='biblio.Usuario'),
        ),
    ]
