# Generated by Django 2.2 on 2020-05-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0008_ejemplar_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Ejemplares',
            field=models.ManyToManyField(to='biblio.Ejemplar'),
        ),
    ]
