# Generated by Django 2.2 on 2020-06-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0009_usuario_ejemplares'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Edad',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
